// Code generated by protoc-gen-twirp v8.1.2, DO NOT EDIT.
// source: user/email.proto

package user

import context "context"
import fmt "fmt"
import http "net/http"
import ioutil "io/ioutil"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

import google_protobuf "google.golang.org/protobuf/types/known/emptypb"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ======================
// EmailService Interface
// ======================

type EmailService interface {
	// VerifyEmail verifies account email by provided code.
	VerifyEmail(context.Context, *VerifyEmailRequest) (*Account, error)

	// SendEmailVerification sends email verification with new code.
	SendEmailVerification(context.Context, *SendEmailVerificationRequest) (*google_protobuf.Empty, error)

	// UpdateEmail updates account email.
	UpdateEmail(context.Context, *UpdateEmailRequest) (*Account, error)
}

// ============================
// EmailService Protobuf Client
// ============================

type emailServiceProtobufClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewEmailServiceProtobufClient creates a Protobuf client that implements the EmailService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewEmailServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) EmailService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "users.email", "EmailService")
	urls := [3]string{
		serviceURL + "VerifyEmail",
		serviceURL + "SendEmailVerification",
		serviceURL + "UpdateEmail",
	}

	return &emailServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *emailServiceProtobufClient) VerifyEmail(ctx context.Context, in *VerifyEmailRequest) (*Account, error) {
	ctx = ctxsetters.WithPackageName(ctx, "users.email")
	ctx = ctxsetters.WithServiceName(ctx, "EmailService")
	ctx = ctxsetters.WithMethodName(ctx, "VerifyEmail")
	caller := c.callVerifyEmail
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *VerifyEmailRequest) (*Account, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VerifyEmailRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VerifyEmailRequest) when calling interceptor")
					}
					return c.callVerifyEmail(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Account)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Account) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *emailServiceProtobufClient) callVerifyEmail(ctx context.Context, in *VerifyEmailRequest) (*Account, error) {
	out := new(Account)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *emailServiceProtobufClient) SendEmailVerification(ctx context.Context, in *SendEmailVerificationRequest) (*google_protobuf.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "users.email")
	ctx = ctxsetters.WithServiceName(ctx, "EmailService")
	ctx = ctxsetters.WithMethodName(ctx, "SendEmailVerification")
	caller := c.callSendEmailVerification
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SendEmailVerificationRequest) (*google_protobuf.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SendEmailVerificationRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SendEmailVerificationRequest) when calling interceptor")
					}
					return c.callSendEmailVerification(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *emailServiceProtobufClient) callSendEmailVerification(ctx context.Context, in *SendEmailVerificationRequest) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *emailServiceProtobufClient) UpdateEmail(ctx context.Context, in *UpdateEmailRequest) (*Account, error) {
	ctx = ctxsetters.WithPackageName(ctx, "users.email")
	ctx = ctxsetters.WithServiceName(ctx, "EmailService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateEmail")
	caller := c.callUpdateEmail
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdateEmailRequest) (*Account, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateEmailRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateEmailRequest) when calling interceptor")
					}
					return c.callUpdateEmail(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Account)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Account) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *emailServiceProtobufClient) callUpdateEmail(ctx context.Context, in *UpdateEmailRequest) (*Account, error) {
	out := new(Account)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ========================
// EmailService JSON Client
// ========================

type emailServiceJSONClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewEmailServiceJSONClient creates a JSON client that implements the EmailService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewEmailServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) EmailService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "users.email", "EmailService")
	urls := [3]string{
		serviceURL + "VerifyEmail",
		serviceURL + "SendEmailVerification",
		serviceURL + "UpdateEmail",
	}

	return &emailServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *emailServiceJSONClient) VerifyEmail(ctx context.Context, in *VerifyEmailRequest) (*Account, error) {
	ctx = ctxsetters.WithPackageName(ctx, "users.email")
	ctx = ctxsetters.WithServiceName(ctx, "EmailService")
	ctx = ctxsetters.WithMethodName(ctx, "VerifyEmail")
	caller := c.callVerifyEmail
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *VerifyEmailRequest) (*Account, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VerifyEmailRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VerifyEmailRequest) when calling interceptor")
					}
					return c.callVerifyEmail(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Account)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Account) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *emailServiceJSONClient) callVerifyEmail(ctx context.Context, in *VerifyEmailRequest) (*Account, error) {
	out := new(Account)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *emailServiceJSONClient) SendEmailVerification(ctx context.Context, in *SendEmailVerificationRequest) (*google_protobuf.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "users.email")
	ctx = ctxsetters.WithServiceName(ctx, "EmailService")
	ctx = ctxsetters.WithMethodName(ctx, "SendEmailVerification")
	caller := c.callSendEmailVerification
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SendEmailVerificationRequest) (*google_protobuf.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SendEmailVerificationRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SendEmailVerificationRequest) when calling interceptor")
					}
					return c.callSendEmailVerification(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *emailServiceJSONClient) callSendEmailVerification(ctx context.Context, in *SendEmailVerificationRequest) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *emailServiceJSONClient) UpdateEmail(ctx context.Context, in *UpdateEmailRequest) (*Account, error) {
	ctx = ctxsetters.WithPackageName(ctx, "users.email")
	ctx = ctxsetters.WithServiceName(ctx, "EmailService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateEmail")
	caller := c.callUpdateEmail
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdateEmailRequest) (*Account, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateEmailRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateEmailRequest) when calling interceptor")
					}
					return c.callUpdateEmail(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Account)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Account) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *emailServiceJSONClient) callUpdateEmail(ctx context.Context, in *UpdateEmailRequest) (*Account, error) {
	out := new(Account)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===========================
// EmailService Server Handler
// ===========================

type emailServiceServer struct {
	EmailService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewEmailServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewEmailServiceServer(svc EmailService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &emailServiceServer{
		EmailService:     svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *emailServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *emailServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// EmailServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const EmailServicePathPrefix = "/twirp/users.email.EmailService/"

func (s *emailServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "users.email")
	ctx = ctxsetters.WithServiceName(ctx, "EmailService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "users.email.EmailService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "VerifyEmail":
		s.serveVerifyEmail(ctx, resp, req)
		return
	case "SendEmailVerification":
		s.serveSendEmailVerification(ctx, resp, req)
		return
	case "UpdateEmail":
		s.serveUpdateEmail(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *emailServiceServer) serveVerifyEmail(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveVerifyEmailJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveVerifyEmailProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *emailServiceServer) serveVerifyEmailJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "VerifyEmail")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(VerifyEmailRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.EmailService.VerifyEmail
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *VerifyEmailRequest) (*Account, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VerifyEmailRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VerifyEmailRequest) when calling interceptor")
					}
					return s.EmailService.VerifyEmail(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Account)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Account) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Account
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Account and nil error while calling VerifyEmail. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *emailServiceServer) serveVerifyEmailProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "VerifyEmail")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(VerifyEmailRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.EmailService.VerifyEmail
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *VerifyEmailRequest) (*Account, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*VerifyEmailRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*VerifyEmailRequest) when calling interceptor")
					}
					return s.EmailService.VerifyEmail(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Account)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Account) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Account
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Account and nil error while calling VerifyEmail. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *emailServiceServer) serveSendEmailVerification(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveSendEmailVerificationJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveSendEmailVerificationProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *emailServiceServer) serveSendEmailVerificationJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SendEmailVerification")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(SendEmailVerificationRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.EmailService.SendEmailVerification
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SendEmailVerificationRequest) (*google_protobuf.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SendEmailVerificationRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SendEmailVerificationRequest) when calling interceptor")
					}
					return s.EmailService.SendEmailVerification(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf.Empty and nil error while calling SendEmailVerification. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *emailServiceServer) serveSendEmailVerificationProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SendEmailVerification")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(SendEmailVerificationRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.EmailService.SendEmailVerification
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SendEmailVerificationRequest) (*google_protobuf.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SendEmailVerificationRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SendEmailVerificationRequest) when calling interceptor")
					}
					return s.EmailService.SendEmailVerification(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf.Empty and nil error while calling SendEmailVerification. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *emailServiceServer) serveUpdateEmail(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveUpdateEmailJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveUpdateEmailProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *emailServiceServer) serveUpdateEmailJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateEmail")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(UpdateEmailRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.EmailService.UpdateEmail
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdateEmailRequest) (*Account, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateEmailRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateEmailRequest) when calling interceptor")
					}
					return s.EmailService.UpdateEmail(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Account)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Account) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Account
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Account and nil error while calling UpdateEmail. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *emailServiceServer) serveUpdateEmailProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateEmail")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(UpdateEmailRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.EmailService.UpdateEmail
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdateEmailRequest) (*Account, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateEmailRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateEmailRequest) when calling interceptor")
					}
					return s.EmailService.UpdateEmail(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Account)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Account) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Account
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Account and nil error while calling UpdateEmail. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *emailServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *emailServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.2"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *emailServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "users.email", "EmailService")
}

var twirpFileDescriptor1 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0x25, 0xfb, 0x3e, 0x75, 0xbb, 0xf3, 0x61, 0x06, 0x9c, 0xa3, 0x0a, 0xca, 0x10, 0x54, 0x84,
	0x14, 0xf4, 0x17, 0xac, 0x32, 0xc5, 0xd7, 0x0e, 0x7d, 0xd8, 0xcb, 0xec, 0x92, 0xbb, 0x11, 0xd8,
	0x9a, 0x9a, 0xa5, 0x1d, 0xfb, 0x57, 0xfe, 0xbe, 0x3e, 0x49, 0xd2, 0x16, 0x3a, 0xa7, 0x82, 0x4f,
	0x2d, 0xf7, 0xdc, 0x7b, 0xce, 0xc9, 0x39, 0xd0, 0x49, 0x57, 0xa8, 0x7d, 0x5c, 0x46, 0x72, 0xc1,
	0x12, 0xad, 0x8c, 0xa2, 0x6d, 0x3b, 0x59, 0x31, 0x37, 0xf2, 0x4e, 0xe7, 0x4a, 0xcd, 0x17, 0xe8,
	0x3b, 0x68, 0x9a, 0xce, 0x7c, 0x5c, 0x26, 0x66, 0x53, 0x6c, 0x7a, 0x27, 0x59, 0xb4, 0x90, 0x22,
	0x32, 0xe8, 0x57, 0x3f, 0x25, 0x40, 0x1d, 0x69, 0xc4, 0xb9, 0x4a, 0x63, 0x53, 0xcc, 0xfa, 0x4f,
	0x70, 0x36, 0xc2, 0x58, 0x0c, 0x2d, 0xed, 0x2b, 0x6a, 0x39, 0x93, 0x3c, 0x32, 0x52, 0xc5, 0x21,
	0xbe, 0xa7, 0xb8, 0x32, 0xf4, 0x0a, 0xa0, 0x3c, 0x98, 0x48, 0xd1, 0x23, 0x17, 0xe4, 0xba, 0x15,
	0x34, 0xf3, 0x60, 0x4f, 0xff, 0xfb, 0x20, 0x24, 0x6c, 0x95, 0xd8, 0xb3, 0xe8, 0x73, 0xa0, 0x2f,
	0x89, 0x15, 0x73, 0x54, 0x7f, 0x3d, 0xa7, 0x97, 0xd0, 0x8a, 0x71, 0x3d, 0x71, 0xcf, 0xeb, 0x35,
	0xdc, 0xde, 0x41, 0x1e, 0xfc, 0xd7, 0x8d, 0x37, 0x12, 0x36, 0x63, 0x5c, 0x3b, 0xd6, 0xfe, 0x00,
	0xa8, 0x33, 0xb9, 0xd9, 0x12, 0xb9, 0x85, 0xa3, 0xac, 0x66, 0x7d, 0xc2, 0x95, 0xc0, 0x42, 0x2b,
	0xec, 0xd4, 0x81, 0x07, 0x25, 0xf0, 0x2e, 0x27, 0x70, 0xe8, 0xae, 0x47, 0xa8, 0x33, 0xc9, 0x91,
	0x3e, 0x42, 0xbb, 0xc6, 0x49, 0xcf, 0x59, 0x2d, 0x68, 0xb6, 0xab, 0xe6, 0x75, 0xcb, 0x85, 0x2a,
	0xc7, 0x41, 0xf1, 0xa5, 0x63, 0x38, 0xfe, 0x36, 0x49, 0x7a, 0xb3, 0xc5, 0xf8, 0x5b, 0xda, 0x5e,
	0x97, 0x15, 0xc5, 0xb2, 0xaa, 0x58, 0x36, 0xb4, 0xc5, 0x5a, 0x8f, 0xb5, 0x70, 0xbf, 0x78, 0xdc,
	0x8d, 0xfd, 0x27, 0x8f, 0x01, 0x8c, 0x9b, 0x3a, 0xe1, 0xbe, 0x05, 0xa7, 0xfb, 0x4e, 0xe3, 0xfe,
	0x33, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xf1, 0x91, 0xba, 0x6b, 0x02, 0x00, 0x00,
}
