// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: compendium/blacklist/v1/service.proto

package blacklistv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on FindBannedWordRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FindBannedWordRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FindBannedWordRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FindBannedWordRequestMultiError, or nil if none found.
func (m *FindBannedWordRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FindBannedWordRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetWord()); l < 1 || l > 255 {
		err := FindBannedWordRequestValidationError{
			field:  "Word",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return FindBannedWordRequestMultiError(errors)
	}

	return nil
}

// FindBannedWordRequestMultiError is an error wrapping multiple validation
// errors returned by FindBannedWordRequest.ValidateAll() if the designated
// constraints aren't met.
type FindBannedWordRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FindBannedWordRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FindBannedWordRequestMultiError) AllErrors() []error { return m }

// FindBannedWordRequestValidationError is the validation error returned by
// FindBannedWordRequest.Validate if the designated constraints aren't met.
type FindBannedWordRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FindBannedWordRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FindBannedWordRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FindBannedWordRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FindBannedWordRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FindBannedWordRequestValidationError) ErrorName() string {
	return "FindBannedWordRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FindBannedWordRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFindBannedWordRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FindBannedWordRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FindBannedWordRequestValidationError{}

// Validate checks the field values on FindBannedWordResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FindBannedWordResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FindBannedWordResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FindBannedWordResponseMultiError, or nil if none found.
func (m *FindBannedWordResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *FindBannedWordResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for WordFound

	if len(errors) > 0 {
		return FindBannedWordResponseMultiError(errors)
	}

	return nil
}

// FindBannedWordResponseMultiError is an error wrapping multiple validation
// errors returned by FindBannedWordResponse.ValidateAll() if the designated
// constraints aren't met.
type FindBannedWordResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FindBannedWordResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FindBannedWordResponseMultiError) AllErrors() []error { return m }

// FindBannedWordResponseValidationError is the validation error returned by
// FindBannedWordResponse.Validate if the designated constraints aren't met.
type FindBannedWordResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FindBannedWordResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FindBannedWordResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FindBannedWordResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FindBannedWordResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FindBannedWordResponseValidationError) ErrorName() string {
	return "FindBannedWordResponseValidationError"
}

// Error satisfies the builtin error interface
func (e FindBannedWordResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFindBannedWordResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FindBannedWordResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FindBannedWordResponseValidationError{}
