// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: compendium/blacklist/v1/service.proto

package blacklistv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindBannedWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *FindBannedWordRequest) Reset() {
	*x = FindBannedWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compendium_blacklist_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBannedWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBannedWordRequest) ProtoMessage() {}

func (x *FindBannedWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compendium_blacklist_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBannedWordRequest.ProtoReflect.Descriptor instead.
func (*FindBannedWordRequest) Descriptor() ([]byte, []int) {
	return file_compendium_blacklist_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *FindBannedWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type FindBannedWordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WordFound bool `protobuf:"varint,1,opt,name=word_found,json=wordFound,proto3" json:"word_found,omitempty"`
}

func (x *FindBannedWordResponse) Reset() {
	*x = FindBannedWordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compendium_blacklist_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBannedWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBannedWordResponse) ProtoMessage() {}

func (x *FindBannedWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compendium_blacklist_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBannedWordResponse.ProtoReflect.Descriptor instead.
func (*FindBannedWordResponse) Descriptor() ([]byte, []int) {
	return file_compendium_blacklist_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *FindBannedWordResponse) GetWordFound() bool {
	if x != nil {
		return x.WordFound
	}
	return false
}

var File_compendium_blacklist_v1_service_proto protoreflect.FileDescriptor

var file_compendium_blacklist_v1_service_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x75, 0x6d, 0x2f, 0x62, 0x6c, 0x61,
	0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x64,
	0x69, 0x75, 0x6d, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31,
	0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x15, 0x46, 0x69, 0x6e,
	0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x0a, 0xfa, 0x42, 0x07, 0x72, 0x05, 0x10, 0x01, 0x18, 0xff, 0x01, 0x52, 0x04, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x37, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64,
	0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x77, 0x6f, 0x72, 0x64, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x77, 0x6f, 0x72, 0x64, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x85, 0x01, 0x0a, 0x10,
	0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x71, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x57, 0x6f,
	0x72, 0x64, 0x12, 0x2e, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x75, 0x6d, 0x2e,
	0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x75, 0x6d, 0x2e,
	0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x79, 0x73, 0x6f, 0x6d, 0x61, 0x64, 0x2f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73,
	0x75, 0x63, 0x6b, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x64, 0x69,
	0x75, 0x6d, 0x2f, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x76, 0x31, 0x3b,
	0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_compendium_blacklist_v1_service_proto_rawDescOnce sync.Once
	file_compendium_blacklist_v1_service_proto_rawDescData = file_compendium_blacklist_v1_service_proto_rawDesc
)

func file_compendium_blacklist_v1_service_proto_rawDescGZIP() []byte {
	file_compendium_blacklist_v1_service_proto_rawDescOnce.Do(func() {
		file_compendium_blacklist_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_compendium_blacklist_v1_service_proto_rawDescData)
	})
	return file_compendium_blacklist_v1_service_proto_rawDescData
}

var file_compendium_blacklist_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_compendium_blacklist_v1_service_proto_goTypes = []interface{}{
	(*FindBannedWordRequest)(nil),  // 0: compendium.blacklist.v1.FindBannedWordRequest
	(*FindBannedWordResponse)(nil), // 1: compendium.blacklist.v1.FindBannedWordResponse
}
var file_compendium_blacklist_v1_service_proto_depIdxs = []int32{
	0, // 0: compendium.blacklist.v1.BlackListService.FindBannedWord:input_type -> compendium.blacklist.v1.FindBannedWordRequest
	1, // 1: compendium.blacklist.v1.BlackListService.FindBannedWord:output_type -> compendium.blacklist.v1.FindBannedWordResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_compendium_blacklist_v1_service_proto_init() }
func file_compendium_blacklist_v1_service_proto_init() {
	if File_compendium_blacklist_v1_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_compendium_blacklist_v1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBannedWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compendium_blacklist_v1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBannedWordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_compendium_blacklist_v1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compendium_blacklist_v1_service_proto_goTypes,
		DependencyIndexes: file_compendium_blacklist_v1_service_proto_depIdxs,
		MessageInfos:      file_compendium_blacklist_v1_service_proto_msgTypes,
	}.Build()
	File_compendium_blacklist_v1_service_proto = out.File
	file_compendium_blacklist_v1_service_proto_rawDesc = nil
	file_compendium_blacklist_v1_service_proto_goTypes = nil
	file_compendium_blacklist_v1_service_proto_depIdxs = nil
}
