// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: peasant/v1/email_verification.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailVerification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId        string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	ExpirationTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
}

func (x *EmailVerification) Reset() {
	*x = EmailVerification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peasant_v1_email_verification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailVerification) ProtoMessage() {}

func (x *EmailVerification) ProtoReflect() protoreflect.Message {
	mi := &file_peasant_v1_email_verification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailVerification.ProtoReflect.Descriptor instead.
func (*EmailVerification) Descriptor() ([]byte, []int) {
	return file_peasant_v1_email_verification_proto_rawDescGZIP(), []int{0}
}

func (x *EmailVerification) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *EmailVerification) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

func (x *EmailVerification) GetExpirationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationTime
	}
	return nil
}

var File_peasant_v1_email_verification_proto protoreflect.FileDescriptor

var file_peasant_v1_email_verification_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x65, 0x61, 0x73, 0x61, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x65, 0x61, 0x73, 0x61, 0x6e, 0x74, 0x2e, 0x76,
	0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa4, 0x01, 0x0a, 0x11, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x73, 0x6f, 0x6d, 0x61, 0x64, 0x2f, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x75, 0x63, 0x6b, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x65,
	0x61, 0x73, 0x61, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_peasant_v1_email_verification_proto_rawDescOnce sync.Once
	file_peasant_v1_email_verification_proto_rawDescData = file_peasant_v1_email_verification_proto_rawDesc
)

func file_peasant_v1_email_verification_proto_rawDescGZIP() []byte {
	file_peasant_v1_email_verification_proto_rawDescOnce.Do(func() {
		file_peasant_v1_email_verification_proto_rawDescData = protoimpl.X.CompressGZIP(file_peasant_v1_email_verification_proto_rawDescData)
	})
	return file_peasant_v1_email_verification_proto_rawDescData
}

var file_peasant_v1_email_verification_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_peasant_v1_email_verification_proto_goTypes = []interface{}{
	(*EmailVerification)(nil),     // 0: peasant.v1.EmailVerification
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_peasant_v1_email_verification_proto_depIdxs = []int32{
	1, // 0: peasant.v1.EmailVerification.expiration_time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_peasant_v1_email_verification_proto_init() }
func file_peasant_v1_email_verification_proto_init() {
	if File_peasant_v1_email_verification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_peasant_v1_email_verification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailVerification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_peasant_v1_email_verification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peasant_v1_email_verification_proto_goTypes,
		DependencyIndexes: file_peasant_v1_email_verification_proto_depIdxs,
		MessageInfos:      file_peasant_v1_email_verification_proto_msgTypes,
	}.Build()
	File_peasant_v1_email_verification_proto = out.File
	file_peasant_v1_email_verification_proto_rawDesc = nil
	file_peasant_v1_email_verification_proto_goTypes = nil
	file_peasant_v1_email_verification_proto_depIdxs = nil
}
